# Generated by Django 5.1.6 on 2025-03-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
